function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    N=0.3333333333333333;
    KoverN=(params(4)/(1/params(1)-1+params(2)))^(1/(1-params(4)));
    Y=N*KoverN^params(4);
    I=N*params(2)*KoverN;
    K=N*KoverN;
    C=Y-I;
    w=(1-params(4))*K^params(4)*N^(-params(4));
    Rk1=params(4)*Y/K;
    params(3)=(1-params(4))*KoverN^params(4)*(1-N)/C;
    ys_(1)=log(Y);
    ys_(2)=log(C);
    ys_(3)=log(K);
    ys_(5)=log(N);
    ys_(4)=log(I);
    ys_(6)=log(w);
    ys_(7)=log(Rk1);
    ys_(8)=0;
    % Auxiliary equations
end
